Repository googleinterns/gpay-group-buy, pull requests merged in 2020-06, with the labels that each got.

#17 Add yaml file for Google App Engine deployment
  .gcloudignore
  app.yaml
Labels: setup

#21 Set up frontend folder
  web/.eslintignore
  web/.eslintrc.json
  web/.gitignore
  web/.prettierrc.js
  web/README.md
  web/package.json
  web/public/favicon.ico
  web/public/index.html
  web/public/logo192.png
  web/public/logo512.png
  web/public/manifest.json
  web/public/robots.txt
  web/src/App.css
  web/src/App.test.tsx
  web/src/App.tsx
  web/src/index.css
  web/src/index.tsx
  web/src/logo.svg
  web/src/react-app-env.d.ts
  web/src/serviceWorker.ts
  web/src/setupTests.ts
  web/tsconfig.json
  web/yarn.lock
Labels: setup

#20 Setup server development environment
  .gcloudignore
  server/.eslintrc.json
  server/.gitignore
  server/.prettierrc.js
  server/README.md
  server/package.json
  server/src/index.ts
  server/tsconfig.json
  server/yarn.lock
Labels: setup

#23 Add Travis CI
  .travis.yml
Labels: setup

#40 Add pre-push hook to server side
  .travis.yml
  server/package.json
  server/yarn.lock
Labels: setup

#39 Fix server start script for production
  server/README.md
  server/package.json
  server/src/index.ts
Labels: review-required, setup

#41 Add folder structure tree to web README
  web/README.md
Labels: documentation

#46 Add missing types for FE deps
  web/package.json
  web/yarn.lock
Labels: review-required

#36 Add error handling in server
  server/src/api/merchants.ts
  server/src/index.ts
  server/tsconfig.json
Labels: review-required, setup

#44 Add server structure description to README.md
  server/README.md
Labels: documentation

#48 Add Card components
  web/.eslintrc.json
  web/src/Routes.tsx
  web/src/components/common/Card.tsx
  web/src/components/common/CardImage.tsx
  web/src/components/common/ListingCard.tsx
  web/src/components/common/ListingPrice.tsx
  web/src/components/common/StrippedCol.tsx
  web/src/components/design-samples/index.tsx
  web/src/index.css
  web/src/interfaces.ts
Labels: frontend, review-required

#49 Fix FE app.yaml for deployment
  web/app.yaml
Labels: review-required

#50 Add commit progress bar
  web/package.json
  web/src/components/common/CommitProgress.tsx
  web/src/components/design-samples/index.tsx
  web/yarn.lock
Labels: frontend, review-required

#53 Add README.md instruction to give access to database from local machine
  server/README.md
Labels: documentation

#62 Remove unused merchant operations
  server/src/api/merchants.ts
  server/src/services/merchants.ts
  server/src/storage/merchants.ts
Labels: backend

#59 Add lazy loading for images
  web/package.json
  web/src/components/common/CardImage.tsx
  web/src/components/common/LazyWrapper.tsx
  web/yarn.lock
Labels: frontend, review-required

#56 Add listings getter
  server/src/api/index.ts
  server/src/api/listings.ts
  server/src/interfaces.ts
  server/src/services/index.ts
  server/src/services/listings.ts
  server/src/storage/datastore.ts
  server/src/storage/index.ts
  server/src/storage/listings.ts
Labels: backend, review-required

#61 Create add merchant API
  server/app.yaml
  server/package.json
  server/src/api/index.ts
  server/src/api/merchants.ts
  server/src/index.ts
  server/src/interfaces.ts
  server/src/services/index.ts
  server/src/services/merchants.ts
  server/src/storage/datastore.ts
  server/src/storage/index.ts
  server/src/storage/merchants.ts
  server/yarn.lock
Labels: backend, merchant, review-required

#64 Add merchant authentication using Firebase
  server/package.json
  server/src/api/merchants.ts
  server/src/custom-typings/express/index.d.ts
  server/src/middleware/merchant-auth.ts
  server/tsconfig.json
  server/yarn.lock
Labels: backend, merchant, review-required

#68 Lazy load ListingCard instead of CardImage
  web/src/components/common/CardImage.tsx
  web/src/components/common/ListingCard.tsx
Labels: bug, frontend, review-required

#65 Add numcommits context and badge
  server/src/interfaces.ts
  web/src/Routes.tsx
  web/src/api.ts
  web/src/components/common/CommitsBadge.tsx
  web/src/components/customer/contexts/CommitCountContext.tsx
  web/src/components/customer/explore/index.tsx
  web/src/constants/customer.ts
  web/src/interfaces.ts
Labels: customer, frontend, review-required

#52 Add functions to check that Merchant Sign Up form data are valid
  web/package.json
  web/src/Routes.tsx
  web/src/components/common/FormRow.tsx
  web/src/components/common/GroupBuyMerchantHeader.tsx
  web/src/components/merchant/sign-up/SignUpCard.tsx
  web/src/components/merchant/sign-up/SignUpForm.tsx
  web/src/components/merchant/sign-up/hooks/useSignUpForm.tsx
  web/src/constants/sign-up-errors.ts
  web/yarn.lock
Labels: frontend, merchant, review-required

#54 Add Firebase authentication for Merchant Sign Up
  web/app.yaml
  web/package.json
  web/src/components/common/FormRow.tsx
  web/src/components/merchant/sign-up/hooks/useSignUpForm.tsx
  web/src/constants/sign-up-errors.ts
  web/src/firebase-auth.ts
  web/yarn.lock
Labels: frontend, merchant, review-required

#70 Add individual listing getter
  server/src/api/listings.ts
  server/src/services/listings.ts
  server/src/storage/listings.ts
Labels: backend, review-required

#79 Add CORS to express router
  server/app.yaml
  server/package.json
  server/src/index.ts
  server/yarn.lock
  web/.env.development
  web/.env.production
Labels: backend, bug

#81 Add dotenv-flow library to read .env file using node
  server/.env.development
  server/.gcloudignore
  server/app.yaml
  server/package.json
  server/yarn.lock
Labels: backend, setup
